//! Small additive response envelope. IDs are opaque strings in the webview.

use crate::runtime::Runtime;
use serde_json::{json, Value};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

static NEXT_REQUEST_ID: AtomicU64 = AtomicU64::new(1);

use crate::aws::{context::VerifiedSession, AwsContext};

#[derive(Default)]
pub(crate) struct RequestEnvelope {
    id: Option<String>,
    context: Option<Value>,
    audit: Option<(Runtime, &'static str, String)>,
    started: bool,
    finished: bool,
}

impl RequestEnvelope {
    pub(crate) fn from_params(params: &Value) -> Result<Self, &'static str> {
        let id = match params.get("request_id") {
            None | Some(Value::Null) => None,
            Some(Value::String(id))
                if !id.is_empty()
                    && id.len() <= 128
                    && id
                        .bytes()
                        .all(|c| c.is_ascii_alphanumeric() || b"._:-".contains(&c)) =>
            {
                Some(id.clone())
            }
            _ => return Err("request_id must be a short ASCII identifier"),
        };
        Ok(Self {
            id,
            context: None,
            audit: None,
            started: false,
            finished: false,
        })
    }

    pub(crate) fn audited(mut self, command: &'static str, runtime: &Runtime) -> Self {
        // Correlation is generated by the app. A client ID is echoed only in
        // its response, never written into diagnostics as arbitrary input.
        let epoch = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let id = format!(
            "req-{epoch:x}-{}",
            NEXT_REQUEST_ID.fetch_add(1, Ordering::Relaxed)
        );
        self.audit = Some((runtime.for_request(&id), command, id));
        self
    }

    pub(crate) fn runtime(&self, fallback: &Runtime) -> Runtime {
        self.audit
            .as_ref()
            .map(|(runtime, _, _)| runtime.clone())
            .unwrap_or_else(|| fallback.clone())
    }

    pub(crate) fn start(&mut self) {
        if !self.started {
            self.started = true;
            self.record("started", None);
        }
    }

    fn record(&self, event: &str, result: Option<&Value>) {
        if let Some((runtime, command, _)) = &self.audit {
            let mut entry = json!({"kind":"request", "command":command, "event":event});
            if let Some(context) = &self.context {
                entry["account_id"] = context["account_id"].clone();
                entry["region"] = context["region"].clone();
            }
            if let Some(error_type) = result
                .and_then(|result| result.get("error_type"))
                .and_then(Value::as_str)
            {
                entry["error_type"] = json!(error_type);
            }
            runtime.audit(entry);
        }
    }

    pub(crate) fn bind(&mut self, context: &AwsContext, session: &VerifiedSession) {
        self.context = Some(json!({
            "context_id": context.id().to_string(),
            "provider_revision": session.provider_revision.to_string(),
            "settings_revision": session.snapshot.settings_revision.to_string(),
            "profile": session.snapshot.profile,
            "account_id": session.identity.account_id,
            "region": session.snapshot.region,
        }));
    }

    pub(crate) fn attach(mut self, mut response: Value) -> Value {
        let outcome = outcome(&response);
        self.record(outcome, Some(&response));
        self.finished = true;
        let mut metadata = self.context.clone().unwrap_or_else(|| {
            json!({
                "context_id": null, "provider_revision": null, "settings_revision": null,
                "profile": null, "account_id": null, "region": null,
            })
        });
        metadata["id"] = json!(self.id);
        metadata["outcome"] = json!(outcome);
        if let Some((_, _, id)) = &self.audit {
            metadata["audit_id"] = json!(id);
        }
        if !response.is_object() {
            response = json!({"render": "raw_json", "data": response});
        }
        response["_request"] = metadata;
        if let Some((runtime, _, _)) = &self.audit {
            response = runtime.with_diagnostics(response);
        }
        response
    }
}

impl Drop for RequestEnvelope {
    fn drop(&mut self) {
        if !self.finished {
            self.record("cancelled", None);
        }
    }
}

/// Application outcome, including legacy and partial error render shapes.
/// Logical cancellation does not certify that remote work stopped.
pub(crate) fn outcome(result: &Value) -> &'static str {
    match result.get("error_type").and_then(Value::as_str) {
        Some("Superseded" | "Cancelled" | "QueryCancelled" | "StaleContext") => return "cancelled",
        Some(
            "InvalidRequest" | "UnsupportedCommand" | "PolicyDenied" | "NoVerifiedContext"
            | "InvalidContext",
        ) => return "denied",
        _ => {}
    }
    if result["render"] == "permission_denied" {
        return "denied";
    }
    if result["ok"] == false
        || result["valid"] == false
        || result["partial"] == true
        || result["status"] == "partial"
        || result["status"] == "failed"
        || [
            result.get("error"),
            result.get("data").and_then(|data| data.get("error")),
        ]
        .into_iter()
        .flatten()
        .any(|error| !error.is_null() && error != "")
    {
        return "failed";
    }
    "succeeded"
}
